[options]
admin_passwd = $pbkdf2-sha512$600000$ptQaYwxBKAUAwJjzHkNI6Q$aE1oGfIah/rUboCH/JT0CCL5pdrAkI5AxmnKn0DOi7bNHfP.i/yV.Y5ZDU2uifZZ2hSQuA33.AZwNDXdDp06wQ
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

